#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: subham7031979@gmail.com
#    password: yurufbdpiamwcwoh
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true